name: Build and Test

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v20.2.0
        uses: actions/setup-node@v2
        with:
          node-version: v20.2.0

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/**/*.xml

      - name: Fail workflow if tests fail
        uses: EnricoMi/failing-workflow@v1
        if: always()
        with:
          condition: ${{ github.event.status != 'failure' && runner.os == 'Linux' }}

